name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass
      
      - name: test pwd
        run:
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "ls &&
          cd test/ &&
          git pull &&
          composer install &&
          php bin/console d:m:m -n"
